### PR TITLE
[#277] Fix: Follow status doesn't show consistently between Article Details screen and Author Profile screen

### LINKED ISSUE #277: Fix: [Backend] Follow status doesn't show consistently between Article Details screen and Author Profile screen
## Issue

Follow status doesn't show consistently between Article Details screen and Author Profile screen that Article Details screen seems to show correctly but Author Profile screen always show as `Not follow` state even after updating.

https://user-images.githubusercontent.com/70877098/144169169-4e41b687-c70c-4a8d-9338-29df4b92fc9c.MP4

## Expected

Follow status should appear consistently between Article Details screen and Author Profile screen and reflect the current Follow status value from API.

## Steps to reproduce

1. Login with valid credentials
2. Open another author's article on Global tab from Home Screen.
3. Follow the author.
4. Select that author name.
5. Observe the result.
6. Update follow status of the author to `Following`.
7. Go back out and go in again.
8. Observe the result.

## Remarks

After further investigation, this seems to be a backend issue that in the sample API response from [here](https://gothinkster.github.io/realworld/docs/specs/backend-specs/api-response-format#profile) for profile, it should include the `following` flag but actually backend responded without the `following` flag as below:
```
---------------------
GET 'https://nimble-medium.herokuapp.com/api/profiles/tester':
cURL:
$ curl -v \
	-X GET \
	-H "Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8" \
	-H "Accept-Language: en-VN;q=1.0, vi-VN;q=0.9, th-VN;q=0.8" \
	-H "User-Agent: Nimble Medium - Staging/1.4.2 (co.nimblehq.nimble-medium-stag; build:1; iOS 15.1.0) Alamofire/5.4.4" \
	-H "X-Requested-With: XMLHttpRequest" \
	"https://nimble-medium.herokuapp.com/api/profiles/tester"
---------------------
200 'https://nimble-medium.herokuapp.com/api/profiles/tester' [1.4643 s]:
Headers: [
  X-Ratelimit-Remaining: 59
  Connection: keep-alive
  Content-Type: application/json
  Cache-Control: no-cache, private
  Date: Wed, 01 Dec 2021 07:44:27 GMT
  X-Ratelimit-Limit: 60
  Transfer-Encoding: Identity
  Vary: Origin
  Via: 1.1 vegur
  Server: Apache
]
Body:
{
  "profile" : {
    "bio" : null,
    "username" : "tester",
    "image" : null
  }
}
```

### PR DESCRIPTION
**Pull request by markgravity**
Resolved #277

## What happened

Fix: Follow status doesn't show consistently between Article Details screen and Author Profile screen

## Insight

n/a

## Proof Of Work

https://user-images.githubusercontent.com/17875522/144532825-28857854-b959-482e-840f-54d7aa34b3c9.mov

### CODE REVIEW

File: NimbleMedium/Sources/Data/Repositories/User/UserRepository.swift [hunk 1]
```diff
@@ -22,7 +22,7 @@ final class UserRepository: UserRepositoryProtocol {
 
     func getUserProfile(username: String) -> Single<Profile> {
         let requestConfiguration = UserRequestConfiguration.profile(username: username)
-        return networkAPI
+        return authenticatedNetworkAPI
```
Comment (minhnimble) [inline NimbleMedium/Sources/Data/Repositories/User/UserRepository.swift:25]: Please help check the case when we call `authenticatedNetworkAPI` without logging in yet. It would be super helpful if you attach the P.o.W for that case as well. Thanks 🙏

**Review by minhnimble — APPROVED** [review]
The rest LGTM 🚀

**Review by suho — APPROVED** [review]
