### PR TITLE
[#242] Handle token expired while using the application

### LINKED ISSUE #242: Fix: The app doesn't redirect to Login screen when the token is expired
## Issue

The app doesn't redirect to Login screen when the token is expired

## Expected

The app redirect to Login screen when the token is expired

## Steps to reproduce

https://user-images.githubusercontent.com/17875522/141401255-1b236060-b150-4cf9-9483-97814b8a543e.mov

Response log
```
*** Overview *** 
URL https://nimble-medium.herokuapp.com/api/articles/test/favorite
Method POST
Response Code 401
Request Start Time Nov 17 2021 - 11:45:59
Duration 1s

*** Request Header *** 
User-Agent Nimble Medium - Staging/1.4.1 (co.nimblehq.nimble-medium-stag; build:1; iOS 15.0.0) Alamofire/5.4.4
Accept-Encoding br;q=1.0, gzip;q=0.9, deflate;q=0.8
Authorization Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTYzNjY5MTE5NSwiZXhwIjoxNjM2NjkxMTk1fQ==.ZTRhMGY5NDU2MTMyN2JlNjRkN2ZmODYwNDc0MWQyNDBiMmNmMWM1MzFhNWNlMWJlNDZkZjE0ZTRiODNjNWViNQ==
Accept-Language en;q=1.0
X-Requested-With XMLHttpRequest


*** Request Body *** 
-

*** Response Header *** 
Server Apache
Transfer-Encoding Identity
Via 1.1 vegur
Cache-Control no-cache, private
Connection keep-alive
Vary Origin,Authorization
Content-Type application/json
Date Wed, 17 Nov 2021 04:46:00 GMT


*** Response Body *** 
{
  "message" : "Unauthenticated."
}

------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by minhnimble**
Resolved #242

## What happened

The app doesn't handle token expires case and users will keep using the old tokens forever.

## Insight

- Clear current user session when the token expires so that users can navigate to login screen via Menu and login again.

- Update all views with the correct user session status.

**Notes:** I am unable to send the user back to login screen using SwiftUI and this seems to be a complex task. For now the app will only update to the correct state when backing out and user has to manually navigate to login screen for re-login.

## Proof Of Work

https://user-images.githubusercontent.com/70877098/142193530-8fb80cc5-40da-46fc-8ecd-4b4c856ba475.MP4

### CODE REVIEW

File: NimbleMedium/Sources/Constants/HTTPStatusCode.swift [hunk 1]
```diff
@@ -0,0 +1,287 @@
...
+//
+//  Created by Minh Pham on 17/11/2021.
+//
+
+import Foundation
+
+/// This is a list of Hypertext Transfer Protocol (HTTP) response status codes.
+/// It includes codes from IETF internet standards, other IETF RFCs, other specifications, and some additional commonly used codes.
+/// The first digit of the status code specifies one of five classes of response; an HTTP client must recognise these five classes at a minimum.
+enum HTTPStatusCode: Int, Error {
```
Comment (suho) [inline NimbleMedium/Sources/Constants/HTTPStatusCode.swift:13]: This enum should belong to Data layer > NetworkAPI.

File: NimbleMedium/Sources/Data/NetworkAPI/Interceptors/AuthenticatedInterceptor.swift [hunk 2]
```diff
@@ -25,4 +25,19 @@ final class AuthenticatedInterceptor: RequestInterceptor {
             completion(.failure(NetworkAPIError.generic))
         }
     }
+
+    func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
+        print("\(#function) : request : \(request), retryCount : \(request.retryCount)")
+        if let status = request.response?.status, status == .unauthorized {
+            NotificationCenter.default.post(name: .unauthorized, object: nil)
+        }
```
Comment (suho) [inline NimbleMedium/Sources/Data/NetworkAPI/Interceptors/AuthenticatedInterceptor.swift:33]: Do we need this logic? You already handle the logic in the function `validate()` above

File: NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift [hunk 3]
```diff
@@ -75,3 +88,18 @@ extension HomeViewModel: HomeViewModelOutput {
         $isSideMenuOpen.asSignal()
     }
 }
+
+extension HomeViewModel {
+
+    private func unauthorizedNotificationTriggered() -> Observable<Void> {
```
Comment (suho) [inline NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift:94]: How about?
```suggestion
    private func logout() -> Observable<Void> {
```

File: NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift [hunk 4]
```diff
@@ -37,11 +37,24 @@ protocol HomeViewModelProtocol: ObservableViewModel {
...
     var output: HomeViewModelOutput { self }
 
+    @Injected var logoutUseCase: LogoutUseCaseProtocol
+
+    @PublishRelayProperty var didReceiveUnauthorized: Signal<Void>
+
     @Published var isSideMenuOpen: Bool = false
+
+    init() {
+        unauthorizedNotificationTrigger
```
Comment (suho) [inline NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift:52]: Do we need this property?
```suggestion
        NotificationCenter.default.rx.notification(.unauthorized)
```

Comment (minhnimble) [reply NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift:52]: actually we can use directly like your suggestion

File: NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift (hunk 3 above)
Comment (minhnimble) [reply NimbleMedium/Sources/Presentation/Modules/Home/HomeViewModel.swift:94]: @suho right now the action is only handling the logout but maybe we need to do other stuffs in the future and thus we should just use the generic name for it imo.

File: NimbleMedium/Sources/Data/NetworkAPI/Interceptors/AuthenticatedInterceptor.swift (hunk 2 above)
Comment (minhnimble) [reply NimbleMedium/Sources/Data/NetworkAPI/Interceptors/AuthenticatedInterceptor.swift:33]: I put this check here for avoid missing handling case, since when debugging sometimes it triggers backend error `.unauthorized` here.

**Review by suho — APPROVED** [review]

**Review by markgravity — APPROVED** [review]
