### PR TITLE
[#208] Fix: Home screen won't update tabs when a user login/logout

### LINKED ISSUE #208: Fix: Home screen won't update tabs when a user login/logout
## Issue

The Home screen won't update tabs when a user login/logout

## Expected

- When login: Home screen shows up 2 tabs: Your Feeds & Global Feeds
- When logout: Home screen only shows the content of Global Feeds tab

## Steps to reproduce

https://user-images.githubusercontent.com/17875522/138393073-d9f62316-ee1a-4855-b507-1998cf2949f9.mov

### PR DESCRIPTION
**Pull request by minhnimble**
Resolved #208 

## What happened

The Home screen won't update tabs when a user login/logout

## Insight

- When login: Home screen shows up 2 tabs: Your Feeds & Global Feeds
- When logout: Home screen only shows the content of Global Feeds tab
- Introduce a shared viewModel: `UserSessionViewModel` for handling the shared session.
- Update unit tests

## Proof Of Work

https://user-images.githubusercontent.com/70877098/139646083-dd7a6a52-446d-4904-b409-c50218f366cd.MP4

All tests are passed:

Screen Shot 2021-11-01 at 15 47 47

### CODE REVIEW

File: NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift [hunk 1]
```diff
@@ -17,20 +17,35 @@ struct SideMenuActionsView: View {
...
+    @EnvironmentObject private var userSessionViewModel: UserSessionViewModel
+
     @State private var isAuthenticated = false
     @State private var isShowingLoginScreen = false
     @State private var isShowingSignupScreen = false
     @State private var isShowingMyProfileScreen = false
     @State private var showLogoutConfirmationAlert = false
 
-    var body: some View {
+    @ViewBuilder var contentsView: some View {
```
Comment (markgravity) [inline NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift:28]: Wonder why we need `@ViewBuilder` here? 🤔

Comment (minhnimble) [reply NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift:28]: @markgravity maybe you can try to remove and see the error for yourself 😅 it is needed otherwise the app can't be built. We are using `if` condition inside `contentsView` so we need it 🙏

Comment (suho) [reply NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift:28]: @minhnimble maybe 
```suggestion
    @ViewBuilder var contentView: some View {
```

**Review by markgravity — APPROVED** [review]
LGTM

**Review by suho — APPROVED** [review]
