### PR TITLE
[#145] Fix: The left menu is still openable in Article Details screen by dragging the screen from left to right

### LINKED ISSUE #145: Fix: The left menu is still openable in Article Details screen by dragging the screen from left to right.
## Issue

The left menu is still openable in Article Details screen by dragging the screen from left to right. Then it causes multiple loading issues on the Article Details screen as well.

## Expected

The left menu won't openable in Article Details screen by dragging the screen from left to right.

## Steps to reproduce

https://user-images.githubusercontent.com/70877098/133774997-e0d4b283-902a-458e-bcaa-23e5b9c88211.MP4

### PR DESCRIPTION
**Pull request by markgravity**
Resolved #145

## What happened

- Disable dragging when FeedsView disappears
- Prevent FeedsView updates when pushing to Detail and dragging to show SideMenu

## Insight

n/a

## Proof Of Work

https://user-images.githubusercontent.com/17875522/134865455-478b0706-f870-4e6c-9a4a-9164ea0f9601.mov

### CODE REVIEW

File: NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift [hunk 1]
```diff
@@ -71,56 +68,96 @@ struct FeedsView: View {
...
+                    )
                 }
-                .enableRefresh()
-                .padding(.top, 16.0)
-            } else {
-                Text(Localizable.feedsNoArticle())
             }
         }
+
+        var detailNavigationLink: some View {
```
Comment (minhnimble) [inline NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift:143]: maybe we can update the name a bit for better clarification:
```suggestion
        var feedDetailNavigationLink: some View {
```

File: NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift [hunk 2]
```diff
@@ -71,56 +68,96 @@ struct FeedsView: View {
...
+        @State var feedRowViewModels: [FeedRowViewModelProtocol] = []
+        @State var isPushDetailActive = false
+        @State var activeDetailID = ""
+
+        var body: some View {
+            Group {
+                if !feedRowViewModels.isEmpty {
+                    ScrollView {
+                        feedRows
+                    }
```
Comment (minhnimble) [inline NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift:95]: can make this one line I think 🙏

**Review by minhnimble — APPROVED** [review]

**Review by suho — APPROVED** [review]
